---
apiVersion: v1
kind: Namespace
metadata:
  name: fortikonnector

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fortikonnector

rules:
  - apiGroups: [""]

    resources:
      [
        "pods",
        "namespaces",
        "nodes",
        "services",
        "virtualmachineinstances",
        "virtualmachines",
      ]
    verbs: ["get", "watch", "list"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fortikonnector
  namespace: fortikonnector

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fortikonnector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fortikonnector
subjects:
  - kind: ServiceAccount
    name: fortikonnector
    namespace: fortikonnector

---
# API Key for the fortigate to use
apiVersion: v1
kind: Secret
metadata:
  name: fortikonnector-apikey
  namespace: fortikonnector
stringData:
  API_KEY: hunter2


---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fortikonnector-cert
spec:
  secretName: fortikonnector-tls-secret
  dnsNames:
  - 10.20.100.156
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortikonnector
  labels:
    app: fortikonnector
spec:
  replicas: 3

  selector:
    matchLabels:
      app: fortikonnector

  template:
    metadata:
      labels:
        app: fortikonnector

    spec:
      containers:
        - name: fortikonnector
          image: ghcr.io/lachlan2k/fortikonnector:main
          pullPolicy: Always
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: fortikonnector-apikey
                  key: API_KEY

            - name: TLS_CERT_FILE
              value: /etc/tls/tls.crt
            - name: TLS_KEY_FILE
              value: /etc/tls/tls.key
          ports:
            - containerPort: 443
              name: https
          volumeMounts:
          - name: tls-cert
            mountPath: /etc/tls
            readOnly: true
      serviceAccountName: fortigate-connector
      automountServiceAccountToken: true

      volumes:
      - name: tls-cert
        secret:
          secretName: fortikonnector-tls-secret


---
apiVersion: v1
kind: Service
metadata:
  name: fortikonnector

spec:
  type: LoadBalancer
  loadBalancerIP: 10.20.100.156
  ports:
  - port: 443
    targetPort: https
    name: https
  selector:
    app: fortikonnector